name: deploy_wazuh_aks

on:
  push:
    branches:
      - main
    paths:
      - "**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate Indexer Cluster Certificates
        run: |
          chmod +x ./wazuh-kubernetes-qbx/wazuh/certs/indexer_cluster/generate_certs.sh
          ./wazuh-kubernetes-qbx/wazuh/certs/indexer_cluster/generate_certs.sh

      - name: Generate Dashboard HTTP Certificates
        run: |
          chmod +x ./wazuh-kubernetes-qbx/wazuh/certs/dashboard_http/generate_certs.sh
          ./wazuh-kubernetes-qbx/wazuh/certs/dashboard_http/generate_certs.sh

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.AZURE_RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.AZURE_AKS_CLUSTER_NAME }}'
          namespace: 'default'

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      - name: Deploy Wazuh to AKS
        run: |
          kubectl apply -k ./wazuh-kubernetes-qbx/envs/eks/

      - name: Verify deployment
        run: |
          kubectl get pods -n default
